---
name: Get Current PR Data
author: Rishav Dhar (@rdhar)
description: "Get current PR data from any event trigger, including: issue_comment, merge_group, push, and workflow_dispatch."

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        # Populate environment variables.
        echo GH_API="X-GitHub-Api-Version:2022-11-28" >> "$GITHUB_ENV"
        echo GH_TOKEN="${{ inputs.token }}" >> "$GITHUB_ENV"
        if [[ "$GITHUB_SERVER_URL" != "https://github.com" ]]; then echo GH_HOST=$(echo "$GITHUB_SERVER_URL" | sed 's/.*:\/\///') >> "$GITHUB_ENV"; fi

    - id: data
      shell: bash
      run: |
        # Fallback on empty string if the branch is not found.
        branch=${{ github.ref_name || github.head_ref || github.ref || '0' }}

        # Get PR number using GitHub API for different event triggers.
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          # List PRs associated with the commit, then get the PR number from the head ref or the latest PR.
          associated_prs=$(gh api /repos/${{ github.repository }}/commits/${GITHUB_SHA}/pulls --header "$GH_API" --method GET --field per_page=100)
          number=$(echo "$associated_prs" | jq --raw-output '(.[] | select(.head.ref == env.GITHUB_REF_NAME) | .number) // .[0].number // 0')
        elif [[ "$GITHUB_EVENT_NAME" == "merge_group" ]]; then
          # Get the PR number by parsing the ref name.
          number=$(echo "${GITHUB_REF_NAME}" | sed -n 's/.*pr-\([0-9]*\)-.*/\1/p')
        else
          # Get the PR number from branch name, otherwise fallback on 0 if the PR number is not found.
          number=${{ github.event.number || github.event.issue.number }} || $(gh api /repos/${{ github.repository }}/pulls --header "$GH_API" --method GET --field per_page=100 --field head="${branch}" | jq '.[0].number // 0')
        fi

        echo "branch=$branch" >> "$GITHUB_OUTPUT"
        echo "number=$number" >> "$GITHUB_OUTPUT"

outputs:
  branch:
    description: "Current PR branch."
    value: ${{ steps.data.outputs.branch }}
  number:
    description: "Current PR number."
    value: ${{ steps.data.outputs.number }}

inputs:
  token:
    default: ${{ github.token }}
    description: "Specify a GitHub token (e.g., `secrets.GITHUB_TOKEN`)."
    required: false

branding:
  color: gray-dark
  icon: git-pull-request
