---
name: Tests

on:
  issue_comment:
  merge_group:
  pull_request:
  pull_request_target:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Echo context
        env:
          GH_JSON: ${{ toJson(github) }}
        run: |
          echo "GITHUB_SHA $GITHUB_SHA"
          echo "GITHUB_REF $GITHUB_REF"
          echo "GITHUB_REF_NAME $GITHUB_REF_NAME"
          echo "$GH_JSON"

      - name: Checkout action
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: action.yml

      - name: PR data
        id: pr
        uses: ./

      - name: Echo data
        run: |
          echo Number "${{ steps.pr.outputs.number }}" from "${{ github.event_name }} event."
          echo Branch "${{ steps.pr.outputs.branch }}" from "${{ github.event_name }} event."
